modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
[[mods]]
modId="steampunk" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Steampunk Armor" #mandatory
description='''
This mod adds new Armor that has Special abilities that are themed around steampunk era equipment.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.steampunk]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.steampunk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"